# Generated by Django 3.2.5 on 2021-11-19 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_tipo', models.CharField(max_length=50)),
                ('idusuario', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
