# Generated by Django 3.2.5 on 2021-12-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='usuario_tipo',
            field=models.CharField(max_length=40),
        ),
    ]
